name: DeployWebPage
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy files to temporal location vía SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        debug: true
        rm: true
        source: "public/*"
        target: "/home/jesus/webCSUTEC/temp/"
    
    - name: move the files from temp location to desire location
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: cp -r /home/jesus/webCSUTEC/temp/public/* /home/csutec/www/.
